LEADERBOARD_ATTRIBUTES = {
    "twitter_connected": {
        "type": "boolean",
        "required": True,
        "default": False,
        "array": False,
    },
    "twitter_user_id": {
        "type": "string",
        "size": 100,
        "required": False,
        "default": None,
        "array": False,
    },
    "twitter_handle": {
        "type": "string",
        "size": 100,
        "required": False,
        "default": None,
        "array": False,
    },
    "twitter_user_name": {
        "type": "string",
        "size": 100,
        "required": False,
        "default": None,
        "array": False,
    },
    "project_name": {
        "type": "string",
        "size": 100,
        "required": True,
        "default": None,
        "array": False,
    },
    "project_description": {
        "type": "string",
        "size": 5000,
        "required": True,
        "default": None,
        "array": False,
    },
    "project_url": {
        "type": "string",
        "size": 500,
        "required": False,
        "default": None,
        "array": False,
    },
    "project_short_url": {
        "type": "string",
        "size": 500,
        "required": False,
        "default": None,
        "array": False,
    },
    "project_demo_url": {
        "type": "string",
        "size": 500,
        "required": True,
        "default": None,
        "array": False,
    },
    "points": {
        "type": "float",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "rank": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "house": {
        "type": "string",
        "size": 100,
        "required": True,
        "default": None,
        "array": False,
    },
    "metric_type": {
        "type": "string",
        "size": 100,
        "required": True,
        "default": None,
        "array": False,
    },
    "last_week_metric": {
        "type": "float",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "this_week_metric": {
        "type": "float",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "metric_change": {
        "type": "float",
        "required": True,
        "min": -100000000,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "search_text": {
        "type": "string",
        "size": 5000,
        "required": True,
        "default": None,
        "array": False,
    },
}
