TWEETS_ATTRIBUTES = {
    "created_on": {
        "type": "datetime",
        "required": True,
        "default": None,
        "array": False,
    },
    "text": {
        "type": "string",
        "size": 500,
        "required": True,
        "default": None,
        "array": False,
    },
    "bookmark_count": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "quote_counts": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "likes": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "reply_counts": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "retweet_counts": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000,
        "default": 0,
        "array": False,
    },
    "language": {
        "type": "string",
        "size": 10,
        "required": True,
        "default": None,
        "array": False,
    },
    "place": {
        "type": "string",
        "size": 1000,
        "required": False,
        "default": None,
        "array": False,
    },
    "media": {
        "type": "string",
        "size": 1000,
        "required": False,
        "default": None,
        "array": True,
    },
    "hashtags": {
        "type": "string",
        "size": 1000,
        "required": False,
        "default": None,
        "array": True,
    },
    "symbols": {
        "type": "string",
        "size": 1000,
        "required": False,
        "default": None,
        "array": True,
    },
    "score": {
        "type": "integer",
        "required": True,
        "min": 0,
        "max": 100000000000,
        "default": 0,
        "array": False,
    },
    "user_id": {
        "type": "string",
        "size": 100,
        "required": True,
        "default": None,
        "array": False,
    },
}
